// Generated by scripts/build-icon-sprite.mjs; Phosphor regular, MIT.
export const iconNames = ["ArrowRight","ArrowLeft","Check","WarningCircle","Info","X","House","MapPin","Books","Lightbulb","Plant","SquaresFour","Tray","Intersect","Bell","UserCircle","List","CaretDown","CaretUp","MagnifyingGlass","Clock","Heart","ChatCircle","Users","ClipboardText","ShieldCheck","ArrowSquareOut","ArrowCounterClockwise","SlidersHorizontal","Plus","CaretRight","CheckCircle","Cube","Gear","SignOut"] as const
export type IconName = typeof iconNames[number]
