export type Screen = { path: string; title: string; group: string; note: string }
export const screens: Screen[] = [
  { path: '/', title: 'Strona główna', group: 'Wejście', note: 'Wizytówka inicjatywy' },
  {
    path: '/logowanie',
    title: 'Logowanie',
    group: 'Wejście',
    note: 'Użytkownik lub administrator',
  },
  {
    path: '/start',
    title: 'Twój punkt wyjścia',
    group: 'Użytkownik',
    note: 'Zgłoszenie i ostatnie sprawy',
  },
  {
    path: '/zgloszenia/nowe',
    title: 'Nowe zgłoszenie',
    group: 'Zgłoszenia',
    note: 'Opis, miejsce i anonimowość',
  },
  {
    path: '/zgloszenia/1/potwierdzenie',
    title: 'Potwierdzenie potrzeby',
    group: 'Zgłoszenia',
    note: 'Korekta sugestii AI i świadome powiązanie',
  },
  {
    path: '/zgloszenia/1/wyniki',
    title: 'Dopasowane rozwiązania',
    group: 'Zgłoszenia',
    note: 'Źródła, ograniczenia, lista i semantyczne 3D',
  },
  {
    path: '/zgloszenia',
    title: 'Moje zgłoszenia',
    group: 'Zgłoszenia',
    note: 'Historia i statusy spraw',
  },
  {
    path: '/zgloszenia/1',
    title: 'Szczegóły zgłoszenia',
    group: 'Zgłoszenia',
    note: 'Oryginał i powiązana potrzeba',
  },
  {
    path: '/innowacje',
    title: 'Biblioteka innowacji',
    group: 'Innowacje',
    note: 'Niezależne przeglądanie i wyszukiwanie',
  },
  {
    path: '/innowacje/bawita',
    title: 'Karta innowacji · BaWita',
    group: 'Innowacje',
    note: 'Opis ze źródła i adaptacja',
  },
  {
    path: '/potrzeby',
    title: 'Potrzeby blisko Ciebie',
    group: 'Potrzeby',
    note: 'Obszar, promień i lista / mapa poglądowa',
  },
  {
    path: '/potrzeby/najczestsze',
    title: 'Najczęściej zgłaszane',
    group: 'Potrzeby',
    note: 'Unikalni zgłaszający, bez wykresu wzrostu',
  },
  {
    path: '/potrzeby/1',
    title: 'Szczegóły potrzeby',
    group: 'Potrzeby',
    note: 'Rozwiązania i możliwości działania',
  },
  {
    path: '/pomysly/nowy',
    title: 'Nowy pomysł',
    group: 'Pomysły',
    note: 'Formularz lub rozmowa z asystentem',
  },
  {
    path: '/pomysly',
    title: 'Pomysły społeczności',
    group: 'Pomysły',
    note: 'Propozycje i prywatne szkice',
  },
  {
    path: '/pomysly/1',
    title: 'Karta pomysłu',
    group: 'Pomysły',
    note: 'AI → autor → administrator',
  },
  {
    path: '/pomysly/1/dyskusja',
    title: 'Rozmowa o pomyśle',
    group: 'Pomysły',
    note: 'Wątek przypięty do propozycji',
  },
  {
    path: '/poparcie',
    title: 'Poparcie propozycji',
    group: 'Pomysły',
    note: 'Gest, przyciski i cofnięcie wyboru',
  },
  {
    path: '/adaptacje/nowa?innowacja=bawita',
    title: 'Adaptacja dla instytucji',
    group: 'Adaptacje',
    note: 'Odbiorcy, zasoby i ograniczenia',
  },
  {
    path: '/adaptacje/1',
    title: 'Robocza adaptacja',
    group: 'Adaptacje',
    note: 'Źródła, kroki i niewiadome',
  },
  {
    path: '/pilotaze',
    title: 'Pilotaże',
    group: 'Pilotaże',
    note: 'Zatwierdzone inicjatywy i udział',
  },
  {
    path: '/pilotaze/1',
    title: 'Szczegóły pilotażu',
    group: 'Pilotaże',
    note: 'Cel, właściciel i plan testów',
  },
  {
    path: '/pilotaze/1/zasoby',
    title: 'Zasoby pilotażu',
    group: 'Pilotaże',
    note: 'Deklaracje czasu, sprzętu, lokalu i budżetu',
  },
  {
    path: '/pilotaze/1/udzial',
    title: 'Udział i lista oczekujących',
    group: 'Pilotaże',
    note: 'Zapis, rezygnacja i oferta miejsca',
  },
  {
    path: '/pilotaze/1/ewaluacja',
    title: 'Ewaluacja',
    group: 'Pilotaże',
    note: 'Satysfakcja i propozycje usprawnień',
  },
  {
    path: '/powiadomienia',
    title: 'Powiadomienia',
    group: 'Użytkownik',
    note: 'Działania wewnątrz aplikacji',
  },
  {
    path: '/moje-aktywnosci',
    title: 'Moje aktywności',
    group: 'Użytkownik',
    note: 'Zgłoszenia, szkice, poparcie i udział',
  },
  {
    path: '/pomoc',
    title: 'Pomoc',
    group: 'Informacje',
    note: 'Objaśnienie najważniejszych przepływów',
  },
  {
    path: '/prywatnosc',
    title: 'Prywatność',
    group: 'Informacje',
    note: 'Dane demo, anonimowość i granica AI',
  },
  {
    path: '/dostepnosc',
    title: 'Dostępność',
    group: 'Informacje',
    note: 'Zaprojektowane ułatwienia i ograniczenia',
  },
  {
    path: '/admin',
    title: 'Pulpit administratora',
    group: 'Administrator',
    note: 'Kolejki wymagające decyzji',
  },
  {
    path: '/admin/zgloszenia',
    title: 'Moderacja zgłoszeń',
    group: 'Administrator',
    note: 'Oryginały i syntetyczna tożsamość',
  },
  {
    path: '/admin/zgloszenia/1',
    title: 'Ocena zgłoszenia',
    group: 'Administrator',
    note: 'Tekst, kontekst i uzasadnienie decyzji',
  },
  {
    path: '/admin/potrzeby',
    title: 'Grupowanie potrzeb',
    group: 'Administrator',
    note: 'Powiązania, obszary i liczniki',
  },
  {
    path: '/admin/potrzeby/1',
    title: 'Scalanie / rozdzielanie',
    group: 'Administrator',
    note: 'Podgląd skutków przed decyzją',
  },
  {
    path: '/admin/innowacje',
    title: 'Baza wiedzy',
    group: 'Administrator',
    note: 'Pochodzenie i stan indeksowania',
  },
  {
    path: '/admin/innowacje/bawita',
    title: 'Redakcja innowacji',
    group: 'Administrator',
    note: 'Metadane, braki i źródła',
  },
  {
    path: '/admin/rozwiazania/duplikaty',
    title: 'Duplikaty rozwiązań',
    group: 'Administrator',
    note: 'Różnice i powiązane głosy',
  },
  {
    path: '/admin/pomysly',
    title: 'Kolejka pomysłów',
    group: 'Administrator',
    note: 'Bramki AI i potwierdzenia autora',
  },
  {
    path: '/admin/pomysly/1',
    title: 'Decyzja o pomyśle',
    group: 'Administrator',
    note: 'Zatwierdzenie lub zwrot z uzasadnieniem',
  },
  {
    path: '/admin/pilotaze',
    title: 'Prowadzenie pilotaży',
    group: 'Administrator',
    note: 'Etapy i gotowość do startu',
  },
  {
    path: '/admin/pilotaze/1',
    title: 'Decyzje o pilotażu',
    group: 'Administrator',
    note: 'Warunki startu i upowszechnienia',
  },
  {
    path: '/admin/pilotaze/1/budzet',
    title: 'Zatwierdzenie budżetu',
    group: 'Administrator',
    note: 'Szacunek, koszt i deklaracje osobno',
  },
  {
    path: '/admin/pilotaze/1/uczestnicy',
    title: 'Uczestnicy i kolejka',
    group: 'Administrator',
    note: 'Umiejętności i oferta wolnego miejsca',
  },
  {
    path: '/marka',
    title: 'Logo i system marki',
    group: 'Marka',
    note: 'Znak, logotyp, kolory i pliki SVG',
  },
]
export const primaryNav = [
  ['/start', 'Start', 'House'],
  ['/potrzeby', 'Potrzeby', 'MapPin'],
  ['/innowacje', 'Innowacje', 'Books'],
  ['/pomysly', 'Pomysły', 'Lightbulb'],
  ['/pilotaze', 'Pilotaże', 'Plant'],
] as const
export const adminNav = [
  ['/admin', 'Przegląd', 'SquaresFour'],
  ['/admin/zgloszenia', 'Zgłoszenia', 'Tray'],
  ['/admin/potrzeby', 'Potrzeby', 'MapPin'],
  ['/admin/innowacje', 'Baza wiedzy', 'Books'],
  ['/admin/rozwiazania/duplikaty', 'Duplikaty', 'Intersect'],
  ['/admin/pomysly', 'Pomysły', 'Lightbulb'],
  ['/admin/pilotaze', 'Pilotaże', 'Plant'],
] as const
